name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      
      - name: Install .NET Wasm tools
        run: dotnet workload install wasm-tools

      - name: Restore Dependecies
        run: dotnet restore src/Champs.Client/Champs.Client.csproj
      
      - name: Build Client
        run: dotnet build -c:Release --no-restore src/Champs.Client/Champs.Client.csproj
      
      - name: Publish Client
        run: dotnet publish -c:Release src/Champs.Client/Champs.Client.csproj -o docs --nologo
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/wwwroot
      
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
    