# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ChampsGame

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Install .NET Wasm tools
        run: dotnet workload install wasm-tools

      - name: Build With .NET
        run: dotnet build --configuration Release

      - name: Publish Client
        run: dotnet publish -c:Release src/Champs.Client/Champs.Client.csproj -o docs --nologo

      - name: Change base-tag in index.html from / to ChampsGame
        run: sed -i 's/<base href="\/" \/>/<base href="\/ChampsGame\/" \/>/g' docs/wwwroot/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/wwwroot
      
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Publish Server
        run: dotnet publish src/Champs.Server/Champs.Server.csproj -c Release -o ${{env.DOTNET_ROOT}}/server

      - name: Upload Server artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_70657587338A401285D6680CC8F5443D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3FE6EF3241E1411B9BB06AB57EBBDAFE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5B041BFA163E4E4083D4E1D14D163F06 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ChampsGame'
          slot-name: 'Production'
          package: .
